#!/system/bin/sh
# Activate compcache (using new sysctl method)

if getprop | grep persist.service.zram; then
	COMPCACHE=`getprop persist.service.zram`
else
	COMPCACHE=`getprop ro.zram.default`
fi

if [ "$COMPCACHE" -ne "0" ]; then
	COMPCACHERAM=$((184 * $COMPCACHE / 100))
	insmod /system/lib/modules/zram.ko
	echo 1 > /sys/block/zram0/reset
	echo "30" > /proc/sys/vm/swappiness
	echo $(($COMPCACHERAM*1024*1024)) > /sys/block/zram0/disksize
	mkswap /dev/block/zram0
	swapon /dev/block/zram0
fi
