#!/system/bin/sh
#
# AMARULLZ DATA TO SD-EXT MOD FOR ANDROID ( AD2SDX )
# ==================================================
#
#  by amarullz [at] yahoo [dot] com
#  xda-developers : amarullz
#  (c) 2011
#  * Oct 19 (ALPHA01)
#  Mod for MIUI v4 ICS by Lennox
#
#  Info: ~ For Changing Log

echo 1 > /sys/class/leds/green/brightness;

EXTFS="auto";

###
# Initializing
###

#-- SDCard Speed Fix
if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]
then
  /system/xbin/echo "8192" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
fi;

#-- Unmount /sd-ext if it already mounted
busybox umount /sd-ext;

#-- Mount /data and move it to /sd-ext
busybox mount /data;
busybox mount --move /data /sd-ext;

#-- Mount sd-ext to /data ( You Will Get 1GB/2GB Internal Memory :D )
busybox mount -t $EXTFS -o noauto_da_alloc,data=ordered,commit=15,barrier=1,nouser_xattr,errors=continue,noatime,nodiratime,nosuid,nodev /dev/block/mmcblk0p2 /data;
busybox chown 1000:1000 /data;
busybox chmod 771 /data;

###[ SDEXT mmcblk0p2 STRICT ]###
# app, app-private, data : should in /data (mmcblk0p2)
#
# ~ ALPHA02 - Add framework_s into (mmcblk0p2) strict 
###
for i in app app-private dalvik-cache data;
do
  #-- If Symlink in /data, delete it
  if [ -h /data/$i ]
  then
    busybox rm /data/$i;
  fi;
    
  #-- If Directory Exists in /sd-ext, move it to /data
  if [ -d /sd-ext/$i ]
  then
    busybox mv /sd-ext/$i /data/;
  fi;
  
  #-- If Directory Not Extst in /data, create it
  if [ ! -d /data/$i ]
  then
    busybox mkdir /data/$i;
    #-- Just Open All Permissions ;)
    busybox chmod 0777 /data/$i;
  fi;
  
  #-- Now Create Symlink From /sd-ext to /data
  if [ ! -h /sd-ext/$i ]
  then
    busybox ln -s /data/$i /sd-ext/$i;
  fi;
done;

###[ INTERNAL mtdblock5 STRICT ]###
# For performance, dalvik-cache should be on /sd-ext
###
#for i in miuiau;
#do
#  #-- If Symlink in /data, delete it
#  if [ -h /sd-ext/$i ]
#  then
#    busybox rm /sd-ext/$i;
#  fi;
    
#  #-- If Directory Exists in /sd-ext, move it to /data
#  if [ -d /data/$i ]
#  then
#    busybox mv /data/$i /sd-ext/;
#  fi;
  
#  #-- If Directory Not Extst in /data, create it
#  if [ ! -d /sd-ext/$i ]
#  then
#    busybox mkdir /sd-ext/$i;
#    #-- Just Open All Permissions ;)
#    busybox chmod 0777 /sd-ext/$i;
#  fi;
  
#  #-- Now Create Symlink From /sd-ext to /data
#  if [ ! -h /data/$i ]
#  then
#    busybox ln -s /sd-ext/$i /data/$i;
#  fi;
#done;

###
# Now create symlink of the rest non Symlink Directories and Files on /sd-ext to /data
#
# ~ ALPHA02 - Fix ls to ls -a, it's ok, because we test -h for symlink
###
cd /sd-ext;
for i in `ls -a`;
do
  if [ $i != ".." -a $i != "." ]
  then
    if [ ! -h /sd-ext/$i ]
    then
      if [ ! -h /data/$i ]
      then
        busybox ln -s /sd-ext/$i /data/$i;
      fi;
    fi;
  fi;
done;
cd /;

###
# It should also need to create the rest non Symlink Directories and Files on /data to /sd-ext
# ~ ALPHA02 - Some Directory may be missing if we don't use it
###
cd /data;
for i in `ls -a`;
do
  if [ $i != ".." -a $i != "." ]
  then
    if [ ! -h /data/$i ]
    then
      if [ ! -h /sd-ext/$i ]
      then
        busybox ln -s /data/$i /sd-ext/$i;
      fi;
    fi;
  fi;
done;
cd /;

###
# Now Important Thing, is to move the com.android* data to /sd-ext (internal) 
# For Good performance. So the system applications will run smooth.
#
# System application will read/write in Internal memory, and 3rd apps will run on sdcard
#
# Notice: Will be affected in 2nd boot :D, so Reboot the system after 1st boot...
###

#-- Prepare data_s in /sd-ext ( For system data )
if [ ! -d /sd-ext/data_s ]
then
  busybox mkdir /sd-ext/data_s;
  #-- Just Open All Permissions ;)
  busybox chmod 0777 /sd-ext/data_s;
fi;

#-- Now Move All com.android* to Internal Memory
cd /data/data/;
for i in `ls -d com.android*`;
do
  #-- Only Non Symlink
  if [ "$i" == "com.android.chrome" ]
  then
	  echo do nothing;
  elif [ "$i" == "com.android.browser" ]
  then
          echo do nothing;
  elif [ "$i" == "com.android.email" ]
  then
          echo do nothing;
  elif [ ! -h /data/data/$i ]
  then
	  busybox mv /data/data/$i /sd-ext/data_s/;
	fi;
done;

#-- Create Symlink of /data/data_s/* to /data/data/ (mmcblk0p2)
cd /sd-ext/data_s/
for i in `ls -d *`;
do
  #-- Only If Symlink Not Exists
  if [ ! -h /data/data/$i ]
  then
	  busybox ln -s /sd-ext/data_s/$i /data/data/$i
	fi;
done;

###
# Now Important Thing, is to move all system dalvik-cache to /sd-ext (internal) 
# For Good performance. So the system applications will run smooth.
#
# System application will read/write in Internal memory, and 3rd apps will run on sdcard
#
# Notice: Will be affected in 2nd boot :D, so Reboot the system after 1st boot...
###

#-- Prepare dalvik-cache_s in /sd-ext ( For system dalvik )
if [ ! -d /sd-ext/dalvik-cache_s ]
then
  busybox mkdir /sd-ext/dalvik-cache_s;
  busybox chmod 0777 /sd-ext/dalvik-cache_s;
fi;

#-- Now Move All system dalvik to Internal Memory
cd /system/app;
for i in `ls *.apk`;
do
  #-- Only Non Symlink
  if [ ! -h /data/dalvik-cache/system@app@$i@classes.dex ]
  then
    busybox mv /data/dalvik-cache/system@app@$i@classes.dex /sd-ext/dalvik-cache_s/;
  fi;
done;
cd /system/framework;
for i in `ls *.apk *.jar`;
do
  #-- Only Non Symlink
  if [ ! -h /data/dalvik-cache/system@framework@$i@classes.dex ]
  then
    busybox mv /data/dalvik-cache/system@framework@$i@classes.dex /sd-ext/dalvik-cache_s/;
  fi;
done;

#-- Create Symlink of /data/dalvik-cache_s/* to /data/dalvik-cache/ (mmcblk0p2)
cd /sd-ext/dalvik-cache_s/
for i in `ls *`;
do
  #-- Only If Symlink Not Exists
  if [ ! -h /data/dalvik-cache/$i ]
  then
    busybox ln -s /sd-ext/dalvik-cache_s/$i /data/dalvik-cache/$i
  fi;
done;

if [ ! -h /system/usr/srec/en-US ]
then
	ln -s /data/usr/srec/en-US /system/usr/srec/en-US;
fi;

echo 0 > /sys/class/leds/green/brightness;
#-- Of Finished.... :D